config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :groups do
    resources :user_transactions
  end
  resources :home
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :user_transactions

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    amount = 0
    user_transactions.each do |transaction|
      amount += transaction.amount
    end
    amount
  end

  def icons
    JSON.parse(File.read('./app/icons/icons.json'))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: 'author_id'
  has_many :user_transactions, foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 250 }
end

app/models/user_transaction.rb
class UserTransaction < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :groups

  validates :name, presence: true
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @groups = Group.where(author_id: current_user.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_resource)
    groups_path
  end
end

app/controllers/user_transactions_controller.rb
class UserTransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_transaction

  def index
    @user_transactions = @group.user_transactions.order(created_at: :desc)
  end

  def new
    @user_transaction = UserTransaction.new
  end

  def create
    @user_transaction = @group.user_transactions.new(user_transaction_params)
    @user_transaction.author_id = current_user.id
    respond_to do |format|
      if @user_transaction.save
        format.html { redirect_to group_user_transactions_path, notice: 'User transaction was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user_transaction
    @group = Group.find(params[:group_id])
  end

  def user_transaction_params
    params.require(:user_transaction).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_transactions_helper.rb
module UserTransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_card.html.erb
<div class= 'gift-credit'>
  <h4>Gift credit</h4>
  <strong>$0</strong>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder:"Category name"%>
  </div>

  <div class="select-field">
   <%= form.select :icon, @group.icons.map { |icon| [icon['name'], icon['url']] },
   { :include_blank => 'Choose category icon' }, :required => true, class:'select-icon' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save category' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<%= link_to group_user_transactions_path(group) do %>
  <div class="category-wrapper">
    <img src="<%= group.icon %>" class="icon">
    <span>
      <h4><%= group.name %></h4>
      <p><%= group.created_at.strftime('%d %b %Y') %></p>
    </span>
    <strong>$<%= group.total_amount %></strong>
  </div>
<% end %>

app/views/groups/index.html.erb
<section class = 'main-section'>
<h1 class="content-header">CATEGORIES</h1>
<%= render 'card' %>
<div class="content-cont">
  <% @groups.each do |group| %>
      <%= render group %>
    <% end %>
</div>

<%= link_to new_group_path do %>
  <div class='content-link'><h5>Add a new category</h5></div>
<% end %>
</section>

app/views/groups/new.html.erb
<section class="main-section">
<h1 class="header">NEW CATEGORY</h1>
<%= render "form", group: @group %>
<div class="links-wrapper"> <%= link_to "Back to Categories", groups_path, class:"link" %></div>
</section>

app/views/home/index.html.erb
<section class = 'main-section'>
  <h1 class = "home-header">Budget App</h1>
  <%= link_to new_user_session_path do %>
    <h3 class = "home-btn login">LOG IN</h3>
  <% end %>

  <%= link_to new_user_registration_path do %>
    <h3 class = "home-btn register">SIGN UP</h3>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/user_transactions/_form.html.erb
<%= form_with model: user_transaction, url: group_user_transactions_path(@group) do |form| %>
  <% if user_transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_transaction.errors.count, "error") %> prohibited this user_transaction from being saved:</h2>

      <ul>
        <% user_transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name , placeholder:"Transaction name", :required => true%>
  </div>

  <div class="field">
    <%= form.number_field :amount , placeholder:"Transaction amount", :required => true, min:'1'%>
  </div>

  <div class="actions">
    <%= form.submit 'Save transaction' %>
  </div>
<% end %>

app/views/user_transactions/_user_transaction.html.erb
<div class="transaction-wrapper">
    <p>Transaction name: <%= user_transaction.name %></p>
    <p>Amount paid: $<%= user_transaction.amount %></p>
    <p>Date of transaction: <%= user_transaction.created_at.strftime('%d %b %Y at %I:%M %p') %></p>
</div>

app/views/user_transactions/index.html.erb
<section class = 'main-section'>
<h1 class="content-header">TRANSACTIONS</h1>
<div class="transaction-category">
  <img src="<%= @group.icon %>">
  <h4><%= @group.name %></h4>
  <strong>$<%= @group.total_amount %></strong>
</div>


<div class="transaction-cont">
  <% @user_transactions.each do |user_transaction| %>
    <%= render user_transaction %>
  <% end %>
</div>

<div class="links-wrapper trans-link"> <%= link_to "Back to categories", groups_path, class:'link' %></div>

<%= link_to new_group_user_transaction_path do %>
  <div class='content-link'><h5>Add a new transaction</h5></div>
<% end %>
</section>

app/views/user_transactions/new.html.erb
<section class="main-section">
<h1 class="header" >NEW TRANSACTION</h1>
<%= render "form", user_transaction: @user_transaction %>

<div class="links-wrapper"> <%= link_to "Back to Transactions", group_user_transactions_path, class:'link' %></div>

</section>